name: Build and Deploy to Static Repo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fuente
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm ci

      - name: Generar build
        run: npm run build

      - name: Clonar repo estático
        run: |
          git config --global user.name "GitHub CI"
          git config --global user.email "ci@github.com"

          git clone https://x-access-token:${{ secrets.STATIC_REPO_TOKEN }}@github.com/leninfabricio29/virys-admin.git build-output
          rm -rf build-output/*
          cp -r dist/* build-output/
          cd build-output
          git add .
          git commit -m "⚡ Update build from CI at $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nada que commitear"
          git push origin main
