name: Build and Deploy to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fuente
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: Generar build
        run: npm run build

      - name: Subir build al servidor f√≠sico
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port:  ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/panicdashboard"
